### ISSUE TITLE
Switching models

### ISSUE THREAD

**Issue by benob** [alumae/gst-kaldi-nnet2-online#4]
gst_kaldinnet2onlinedecoder_deallocate() doesn't deallocate anything, however there are use cases where we would like to cleanly deallocate models and load other models. Could that function do what it is intended for?

**Comment by alumae** [comment]
I use the pugin in my project https://github.com/alumae/kaldi-gstreamer-server. After each request, I have to reset the pipeline, which I do by setting the state of the pipeline to NULL (see https://github.com/alumae/kaldi-gstreamer-server/blob/master/kaldigstserver/decoder2.py#L139):

    pipeline.set_state(Gst.State.NULL)

This also triggers the deallocate method. I don't want to reload the models after each request, hence such hack. 

I must say that I don't fully understand the lifecycle of a GStreamer component, maybe there is better way to do it.

Also, the required sample rate of the incoming audio depends on the acoustic model. So, when switching a model, we would need to renegotiate the GStreamer "pads", which is quite complicated.

If you need to switch models, you can instead create a new instance of the kaldinnet2onlinedecoder plugin, and connect it to your pipeline at run time.

**Comment by benob** [comment]
For some reason, setting the pipeline state to NULL freezes my program. Also, if I create another instance of the plugin, it won't deallocate the resources from the first one.

**Comment by alumae** [comment]
Resources should be released when the plugin is freed (= garbage collected when using python). This should trigger gst_kaldinnet2onlinedecoder_finalize (https://github.com/alumae/gst-kaldi-nnet2-online/blob/master/src/gstkaldinnet2onlinedecoder.cc#L924).

About freezing pipeline: I have also experienced it during the development of the kaldi-gstreamer-server. Are you using python? Maybe you can create a small test program that demonstrates it, I might be able to help.

**Comment by rikrd** [comment]
Another way this could be done is loading the models/graphs etc... in the parameter set callback.  And only reload the model if the filename has changed.

From my point of view, the decoding graph should not be loaded at allocate, since it is not a stream-specific parameter.  I would even say that the model neither, since it does not depend on the stream (though this one is a bit more tricky, since the model is tied to a specific samplerate).

I have modified this in my fork, however a pull request might be a bit messy, since the changes may be quite difficult to cherrypick (they are mixed with changes that allow phone-level alignment).

**Comment by alumae** [comment]
I would happy to merge this. But could you separate the phone-level alignment and model switching functionality to individual PRs?

**Comment by alumae** [comment]
I also implemented the dynamic changing for the lm-fst and big-lm-const-arpa properties. I haven't tested it very carefully though.
